from enum import Enum

class ChoiceEnum(Enum):
    @classmethod
    def choices(cls):
        return tuple((i.name, i.value) for i in cls)

class Gender(ChoiceEnum):
    F = 'Female'
    M = 'Male'
    X = 'Non binary'

class Race(ChoiceEnum):
    A = 'American Indian/Alaskan Native'
    S = 'Asian'
    B = 'Black/African American'
    P = 'Native Hawaiian/Other Pacific Islander'
    W = 'White'
    O = 'Other Race'
    X = 'Prefer not to specify'

class Ethnicity(ChoiceEnum):
    H = 'Hispanic'
    N = 'Non-hispanic'
    X = 'Prefer not to specify'

class AddressType(ChoiceEnum):
    H = 'Home'
    C = 'Current/Temporary'
    P = 'Permanet'
    M = 'Mailing'

class States(ChoiceEnum):
    AL = 'Alabama'
    AK = 'Alaska'
    AS = 'American Samoa'
    AZ = 'Arizona'
    AR = 'Arkansas'
    CA = 'California'
    CO = 'Colorado'
    CT = 'Connecticut'
    DE = 'Delaware'
    DC = 'District of Columbia'
    FL = 'Florida'
    GA = 'Georgia'
    GU = 'Guam'
    HI = 'Hawaii'
    ID = 'Idaho'
    IL = 'Illinois'
    IN = 'Indiana'
    IA = 'Iowa'
    KS = 'Kansas'
    KY = 'Kentucky'
    LA = 'Louisiana'
    ME = 'Maine'
    MD = 'Maryland'
    MA = 'Massachusetts'
    MI = 'Michigan'
    MN = 'Minnesota'
    MS = 'Mississippi'
    MO = 'Missouri'
    MT = 'Montana'
    NE = 'Nebraska'
    NV = 'Nevada'
    NH = 'New Hampshire'
    NJ = 'New Jersey'
    NM = 'New Mexico'
    NY = 'New York'
    NC = 'North Carolina'
    ND = 'North Dakota'
    MP = 'Northern Mariana Islands'
    OH = 'Ohio'
    OK = 'Oklahoma'
    OR = 'Oregon'
    PA = 'Pennsylvania'
    PR = 'Puerto Rico'
    RI = 'Rhode Island'
    SC = 'South Carolina'
    SD = 'South Dakota'
    TN = 'Tennessee'
    TX = 'Texas'
    UT = 'Utah'
    VT = 'Vermont'
    VI = 'Virgin Islands'
    VA = 'Virginia'
    WA = 'Washington'
    WV = 'West Virginia'
    WI = 'Wisconsin'
    WY = 'Wyoming'