# Generated by Django 3.1.7 on 2021-04-17 21:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phone_field.models
import vms_app.models.user
import vms_app.models.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEligibilityQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', vms_app.models.utils.CleanCharField(max_length=10)),
                ('language', vms_app.models.utils.CleanCharField(max_length=20)),
                ('question', vms_app.models.utils.CleanCharField(max_length=255)),
                ('explanation', models.TextField()),
                ('gender', vms_app.models.utils.CleanCharField(choices=[('F', 'Female'), ('M', 'Male'), ('X', 'Non binary')], default='F', max_length=1)),
                ('bool', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('dbid', models.CharField(default=vms_app.models.utils.GenerateDBID, max_length=11, unique=True)),
                ('person', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', vms_app.models.utils.CleanCharField(max_length=100)),
                ('last_name', vms_app.models.utils.CleanCharField(max_length=100)),
                ('middle_initial', vms_app.models.utils.CleanCharField(max_length=1)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('X', 'Non binary')], default='F', max_length=1)),
                ('race', multiselectfield.db.fields.MultiSelectField(choices=[('A', 'American Indian/Alaskan Native'), ('S', 'Asian'), ('B', 'Black/African American'), ('P', 'Native Hawaiian/Other Pacific Islander'), ('W', 'White'), ('O', 'Other Race'), ('X', 'Prefer not to specify')], default='X', max_length=13)),
                ('ethnicity', models.CharField(choices=[('H', 'Hispanic'), ('N', 'Non-hispanic'), ('X', 'Prefer not to specify')], default='X', max_length=1)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('street', vms_app.models.user.NoCommaField(max_length=100)),
                ('city', vms_app.models.utils.CleanCharField(max_length=100)),
                ('zip_code', vms_app.models.utils.CleanCharField(max_length=5)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='NJ', max_length=2)),
                ('address_type', models.CharField(choices=[('H', 'Home'), ('C', 'Current/Temporary'), ('P', 'Permanent'), ('M', 'Mailing')], default='H', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipCode', models.CharField(max_length=5)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='NJ', max_length=2)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', vms_app.models.utils.CleanCharField(max_length=100)),
                ('first_name', vms_app.models.utils.CleanCharField(max_length=100)),
                ('phone_number', vms_app.models.utils.CleanCharField(max_length=40, null=True)),
                ('email', vms_app.models.utils.CleanCharField(max_length=60)),
                ('password', models.CharField(max_length=60, null=True)),
                ('HIPAACert', models.DateTimeField(blank=True, null=True)),
                ('medical_id', models.IntegerField(blank=True, null=True)),
                ('role', vms_app.models.utils.CleanCharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daysUntilNext', models.IntegerField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VaccineBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('expiration', models.DateTimeField(null=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.site')),
                ('vaccineType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.vaccinetype')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationName', models.CharField(default=None, max_length=50, null=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.site')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('duration', models.SmallIntegerField(verbose_name=3)),
                ('capacity', models.IntegerField()),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.site')),
                ('vaccineType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.vaccinetype')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'ADMIN'), ('V', 'VACCINATOR'), ('S', 'SUPPORT STAFF')], default=None, max_length=1, null=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vms_app.site')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalEligibilityAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.DateTimeField()),
                ('answer_bool', models.BooleanField(null=True)),
                ('answer_text', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms_app.patient')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms_app.medicaleligibilityquestion')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalEligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', vms_app.models.utils.CleanCharField(choices=[('S', 'Screening'), ('E', 'Eligibility')], max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms_app.medicaleligibilityquestion')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms_app.site')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('ipAddress', models.CharField(max_length=40)),
                ('webRequest', models.CharField(max_length=64)),
                ('tableName', models.CharField(max_length=100)),
                ('alteredObject', models.TextField(blank=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administered', models.CharField(max_length=2, null=True)),
                ('location', models.CharField(choices=[('LUA', 'Left Upper Arm'), ('LD', 'Left Deltoid'), ('LGM', 'Left Gluteous Medius'), ('LLF', 'Left Lower Forearm'), ('LT', 'Left Thigh'), ('LVL', 'Left Vastus Lateralis'), ('RUA', 'Right Upper Arm'), ('RD', 'Right Deltoid'), ('RGM', 'Right Gluteous Medius'), ('RLF', 'Right Lower Forearm'), ('RT', 'Right Thigh'), ('RVL', 'Right Vastus Lateralis')], max_length=3, null=True)),
                ('signIn', models.DateTimeField(null=True)),
                ('timeVax', models.DateTimeField(null=True)),
                ('secondDose', models.BooleanField()),
                ('notes', models.TextField(default='')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.patient')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms_app.slot')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.station')),
                ('vaccinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.staff')),
                ('vaccine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.vaccinebatch')),
            ],
        ),
    ]
