# Generated by Django 3.1.7 on 2021-04-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
