# Generated by Django 3.1.7 on 2021-04-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='stationName',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
