# Generated by Django 3.1.7 on 2021-04-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='given_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_initial',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
