# Generated by Django 3.1.7 on 2021-04-06 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vms_app", "0002_auto_20210406_0258"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("A", "ADMIN"),
                            ("V", "VACCINATOR"),
                            ("S", "SUPPORT STAFF"),
                        ],
                        default=None,
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vms_app.site",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vms_app.role",
            ),
        ),
    ]
