# Generated by Django 3.1.7 on 2021-04-15 03:37

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0002_auto_20210414_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
