# Generated by Django 3.1.7 on 2021-04-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0002_remove_medicaleligibilityanswer_answer_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaleligibilityanswer',
            name='answer_bool',
            field=models.BooleanField(null=True),
        ),
    ]
