# Generated by Django 3.1.7 on 2021-04-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vms_app", "0003_auto_20210406_0433"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="site",
        ),
        migrations.RemoveField(
            model_name="slot",
            name="site",
        ),
        migrations.RemoveField(
            model_name="slot",
            name="vaccineType",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="role",
        ),
        migrations.RemoveField(
            model_name="station",
            name="site",
        ),
        migrations.RemoveField(
            model_name="vaccinebatch",
            name="site",
        ),
        migrations.RemoveField(
            model_name="vaccinebatch",
            name="vaccineType",
        ),
        migrations.DeleteModel(
            name="Dose",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="Site",
        ),
        migrations.DeleteModel(
            name="Slot",
        ),
        migrations.DeleteModel(
            name="Staff",
        ),
        migrations.DeleteModel(
            name="Station",
        ),
        migrations.DeleteModel(
            name="VaccineBatch",
        ),
        migrations.DeleteModel(
            name="VaccineType",
        ),
    ]
