# Generated by Django 3.1.7 on 2021-04-17 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import vms_app.models.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vms_app', '0004_auto_20210415_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='password',
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicaleligibility',
            name='type',
            field=vms_app.models.utils.CleanCharField(choices=[('S', 'Screening'), ('E', 'Eligibility')], max_length=1),
        ),
        migrations.AlterField(
            model_name='medicaleligibilityquestion',
            name='gender',
            field=vms_app.models.utils.CleanCharField(choices=[('F', 'Female'), ('M', 'Male'), ('X', 'Non binary')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='medicaleligibilityquestion',
            name='label',
            field=vms_app.models.utils.CleanCharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='medicaleligibilityquestion',
            name='language',
            field=vms_app.models.utils.CleanCharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medicaleligibilityquestion',
            name='question',
            field=vms_app.models.utils.CleanCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_type',
            field=models.CharField(choices=[('H', 'Home'), ('C', 'Current/Temporary'), ('P', 'Permanent'), ('M', 'Mailing')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vms_app.role'),
        ),
    ]
