# Generated by Django 3.1.7 on 2021-04-08 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0004_auto_20210406_0437'),
        ('vms_app', '0002_auto_20210407_2315'),
    ]

    operations = [
    ]
