# Generated by Django 3.1.7 on 2021-04-17 01:39

from django.db import migrations, models
import vms_app.models.utils

import sys
sys.path.append('/code/vms_app/models')
from utils import GenerateDBID


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0004_auto_20210415_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dbid',
            field=models.CharField(default=GenerateDBID, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='medicaleligibility',
            name='type',
            field=vms_app.models.utils.CleanCharField(choices=[('S', 'Screening'), ('E', 'Eligibility')], max_length=1),
        ),
        migrations.AlterField(
            model_name='medicaleligibilityquestion',
            name='gender',
            field=vms_app.models.utils.CleanCharField(choices=[('F', 'Female'), ('M', 'Male'), ('X', 'Non binary')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='medicaleligibilityquestion',
            name='label',
            field=vms_app.models.utils.CleanCharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='medicaleligibilityquestion',
            name='language',
            field=vms_app.models.utils.CleanCharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medicaleligibilityquestion',
            name='question',
            field=vms_app.models.utils.CleanCharField(max_length=255),
        ),
    ]
