# Generated by Django 3.1.7 on 2021-04-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms_app", "0005_auto_20210407_1914"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccinebatch",
            name="expiration",
            field=models.DateTimeField(null=True),
        ),
    ]
