# Generated by Django 3.1.7 on 2021-04-08 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0005_merge_20210408_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daysUntilNext', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='first_name',
            new_name='givenName',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='last_name',
            new_name='surName',
        ),
        migrations.RemoveField(
            model_name='site',
            name='email',
        ),
        migrations.RemoveField(
            model_name='site',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='medical_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='station',
            name='station_name',
        ),
        migrations.AddField(
            model_name='site',
            name='zipCode',
            field=models.CharField(default='234234', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='medicalId',
            field=models.DecimalField(decimal_places=0, default='3452', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='phoneNumber',
            field=models.CharField(default='54334-3452-2345', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='stationName',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='comments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='NJ', max_length=2),
        ),
        migrations.AlterField(
            model_name='staff',
            name='HIPAACert',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='123456', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.site'),
        ),
        migrations.CreateModel(
            name='VaccineBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.site')),
                ('vaccineType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.vaccinetype')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('duration', models.SmallIntegerField(verbose_name=3)),
                ('capacity', models.IntegerField()),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.site')),
                ('vaccineType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.vaccinetype')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'ADMIN'), ('V', 'VACCINATOR'), ('S', 'SUPPORT STAFF')], default=None, max_length=1, null=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vms_app.site')),
            ],
        ),
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('administered', models.CharField(max_length=2)),
                ('location', models.CharField(choices=[('LUA', 'Left Upper Arm'), ('LD', 'Left Deltoid'), ('LGM', 'Left Gluteous Medius'), ('LLF', 'Left Lower Forearm'), ('LT', 'Left Thigh'), ('LVL', 'Left Vastus Lateralis'), ('RUA', 'Right Upper Arm'), ('RD', 'Right Deltoid'), ('RGM', 'Right Gluteous Medius'), ('RLF', 'Right Lower Forearm'), ('RT', 'Right Thigh'), ('RVL', 'Right Vastus Lateralis')], max_length=3)),
                ('signIn', models.DateTimeField()),
                ('timeVax', models.DateTimeField()),
                ('secondDose', models.BooleanField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.patient')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms_app.slot')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.station')),
                ('vaccinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.staff')),
                ('vaccine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.vaccinebatch')),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vms_app.role'),
        ),
    ]
