# Generated by Django 3.1.7 on 2021-04-17 01:41

from django.db import migrations

import sys
sys.path.append('/code/vms_app/models')
from utils import GenerateDBID



def gen_dbid(apps, schema_editor):
    Patient = apps.get_model('vms_app', 'Patient')
    for row in Patient.objects.all():
        row.dbid = GenerateDBID()
        row.save(update_fields=['dbid'])

class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0005_auto_20210416_2139'),
    ]

    operations = [
         migrations.RunPython(gen_dbid, reverse_code=migrations.RunPython.noop),
    ]
