# Generated by Django 3.1.7 on 2021-04-17 01:41

from django.db import migrations, models

import sys
sys.path.append('/code/vms_app/models')
from utils import GenerateDBID

class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0006_auto_20210416_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dbid',
            field=models.CharField(default=GenerateDBID, max_length=11, unique=True),
        ),
    ]
