# Generated by Django 3.1.7 on 2021-04-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vms_app", "0006_vaccinebatch_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dose",
            name="administered",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="dose",
            name="amount",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="dose",
            name="location",
            field=models.CharField(
                choices=[
                    ("LUA", "Left Upper Arm"),
                    ("LD", "Left Deltoid"),
                    ("LGM", "Left Gluteous Medius"),
                    ("LLF", "Left Lower Forearm"),
                    ("LT", "Left Thigh"),
                    ("LVL", "Left Vastus Lateralis"),
                    ("RUA", "Right Upper Arm"),
                    ("RD", "Right Deltoid"),
                    ("RGM", "Right Gluteous Medius"),
                    ("RLF", "Right Lower Forearm"),
                    ("RT", "Right Thigh"),
                    ("RVL", "Right Vastus Lateralis"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dose",
            name="signIn",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="dose",
            name="timeVax",
            field=models.DateTimeField(null=True),
        ),
    ]
